before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/openblind
    binary: '{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=netgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'