on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  release:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: vet
        run: go vet ./...

      - name: tests
        run: go test -v -race ./...